repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the latest tag from https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest tag from https://github.com/psf/black/releases
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Use the latest tag from https://github.com/pre-commit/mirrors-mypy/releases
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4  # Use the latest tag from https://github.com/pycqa/flake8/releases
    hooks:
      - id: flake8
